markdown: rdiscount
permalink: /:title/
url: http://devopser.top
baseurl: /blog
name: devopser.top
author: doclaim
qq: 540587562
email: 540587562@qq.com
duoshuo: doclaim
beian: 浙ICP备12026616号
cnzz: 119959
github: devopser
pygments: true
safe: true
paginate: 20
about: "Jekyll @ GitHub。<br /><br />"
